"""
API contract conformance tests — per INTEGRATION_GUIDE.md §4.

Tests fire real requests against the mock-backed server and assert the
response validates against API_CONTRACT.md's JSON shapes.
"""

import sys
from pathlib import Path

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient

# Ensure project root is in sys.path so ai_service imports work
_project_root = str(Path(__file__).resolve().parent.parent.parent)
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from app.main import app  # noqa: E402

# A tiny 1x1 red RGB PNG encoded in base64 — generated by Pillow, verified to roundtrip
_TINY_PNG_BASE64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4z8AAAAMBAQDJ/pLvAAAAAElFTkSuQmCC"
)


@pytest_asyncio.fixture
async def client():
    """Async HTTP client wired to the FastAPI app."""
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        yield ac


# -------------------------------------------------------------------------
# Health endpoint
# -------------------------------------------------------------------------
class TestHealth:
    """GET /api/v1/health — API_CONTRACT.md §1."""

    @pytest.mark.asyncio
    async def test_health_returns_ok(self, client):
        response = await client.get("/api/v1/health")
        assert response.status_code == 200

        data = response.json()
        assert data["status"] == "ok"
        assert isinstance(data["rsunivlm_loaded"], bool)
        assert isinstance(data["fusion_loaded"], bool)


# -------------------------------------------------------------------------
# Query endpoint — valid requests
# -------------------------------------------------------------------------
class TestQueryValid:
    """POST /api/v1/query — valid requests per API_CONTRACT.md §2."""

    @pytest.mark.asyncio
    async def test_vqa_single_image(self, client):
        """VQA: single optical image + question → answer with evidence type 'none'."""
        payload = {
            "query": "How many basketball courts are visible?",
            "images": [
                {
                    "id": "img1",
                    "modality": "optical",
                    "url_or_base64": _TINY_PNG_BASE64,
                }
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 200

        data = response.json()
        # Required top-level fields
        assert "answer" in data
        assert isinstance(data["answer"], str)
        assert 0.0 <= data["confidence"] <= 1.0
        assert data["task"] == "vqa"

        # Visual evidence
        ve = data["visual_evidence"]
        assert ve["type"] == "none"
        assert ve["boxes"] is None
        assert ve["mask_base64"] is None
        assert ve["overlay_base64"] is None

        # Execution summary — always present (CONTRACT.md §7)
        es = data["execution_summary"]
        assert es["selected_task"] == "vqa"
        assert es["tool_used"] == "rsunivlm_vqa"
        assert isinstance(es["parameters"], dict)
        assert es["inputs_validated"] is True
        assert isinstance(es["latency_ms"], int)

    @pytest.mark.asyncio
    async def test_captioning_single_image(self, client):
        """Captioning: query with 'describe' → captioning task."""
        payload = {
            "query": "Describe what you see in this satellite image.",
            "images": [
                {
                    "id": "img1",
                    "modality": "optical",
                    "url_or_base64": _TINY_PNG_BASE64,
                }
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 200

        data = response.json()
        assert data["task"] == "captioning"
        assert data["visual_evidence"]["type"] == "none"
        assert "execution_summary" in data

    @pytest.mark.asyncio
    async def test_detection_bbox(self, client):
        """Detection: query with 'find' → detection with bbox."""
        payload = {
            "query": "Find the water body in this image.",
            "images": [
                {
                    "id": "img1",
                    "modality": "optical",
                    "url_or_base64": _TINY_PNG_BASE64,
                }
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 200

        data = response.json()
        assert data["task"] == "detection"
        ve = data["visual_evidence"]
        assert ve["type"] in ("bbox", "mask")
        assert "execution_summary" in data

    @pytest.mark.asyncio
    async def test_detection_mask(self, client):
        """Detection: query with 'highlight' → detection with mask."""
        payload = {
            "query": "Highlight the water bodies in this image.",
            "images": [
                {
                    "id": "img1",
                    "modality": "optical",
                    "url_or_base64": _TINY_PNG_BASE64,
                }
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 200

        data = response.json()
        assert data["task"] == "detection"
        ve = data["visual_evidence"]
        assert ve["type"] == "mask"
        assert ve["mask_base64"] is not None

    @pytest.mark.asyncio
    async def test_change_detection(self, client):
        """Change detection: 2 optical images with different dates."""
        payload = {
            "query": "What changed between these two dates?",
            "images": [
                {
                    "id": "img1",
                    "modality": "optical",
                    "date": "2023-01-15",
                    "url_or_base64": _TINY_PNG_BASE64,
                },
                {
                    "id": "img2",
                    "modality": "optical",
                    "date": "2024-03-02",
                    "url_or_base64": _TINY_PNG_BASE64,
                },
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 200

        data = response.json()
        assert data["task"] == "change_detection"
        assert "execution_summary" in data

    @pytest.mark.asyncio
    async def test_fusion(self, client):
        """Fusion: 1 optical + 1 SAR image."""
        payload = {
            "query": "Use optical and SAR to identify built-up regions.",
            "images": [
                {
                    "id": "img1",
                    "modality": "optical",
                    "url_or_base64": _TINY_PNG_BASE64,
                },
                {
                    "id": "img2",
                    "modality": "sar",
                    "url_or_base64": _TINY_PNG_BASE64,
                },
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 200

        data = response.json()
        assert data["task"] == "fusion"
        assert data["visual_evidence"]["type"] == "mask"
        assert "execution_summary" in data


# -------------------------------------------------------------------------
# Query endpoint — error cases
# -------------------------------------------------------------------------
class TestQueryErrors:
    """POST /api/v1/query — error responses per API_CONTRACT.md §1."""

    def _assert_error_shape(self, data: dict, expected_code: str) -> None:
        """Assert the response matches the contracted error JSON shape."""
        assert "error" in data
        err = data["error"]
        assert err["code"] == expected_code
        assert isinstance(err["message"], str)
        # detail is optional
        assert "detail" not in err or err["detail"] is None or isinstance(err["detail"], str)

    @pytest.mark.asyncio
    async def test_no_images(self, client):
        """Zero images → 400 INVALID_IMAGE_COUNT."""
        payload = {"query": "test", "images": []}
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 422  # Pydantic min_length=1 rejects this

    @pytest.mark.asyncio
    async def test_too_many_images(self, client):
        """3 images → 400 INVALID_IMAGE_COUNT."""
        payload = {
            "query": "test",
            "images": [
                {"id": f"img{i}", "modality": "optical", "url_or_base64": _TINY_PNG_BASE64}
                for i in range(3)
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 422  # Pydantic max_length=2 rejects this

    @pytest.mark.asyncio
    async def test_two_optical_without_dates(self, client):
        """2 optical images without dates → 400 INVALID_MODALITY_COMBINATION."""
        payload = {
            "query": "What changed?",
            "images": [
                {"id": "img1", "modality": "optical", "url_or_base64": _TINY_PNG_BASE64},
                {"id": "img2", "modality": "optical", "url_or_base64": _TINY_PNG_BASE64},
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 400
        self._assert_error_shape(response.json(), "INVALID_MODALITY_COMBINATION")

    @pytest.mark.asyncio
    async def test_two_optical_same_date(self, client):
        """2 optical images with same date → 400 INVALID_MODALITY_COMBINATION."""
        payload = {
            "query": "What changed?",
            "images": [
                {"id": "img1", "modality": "optical", "date": "2023-01-15", "url_or_base64": _TINY_PNG_BASE64},
                {"id": "img2", "modality": "optical", "date": "2023-01-15", "url_or_base64": _TINY_PNG_BASE64},
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 400
        self._assert_error_shape(response.json(), "INVALID_MODALITY_COMBINATION")

    @pytest.mark.asyncio
    async def test_two_sar_images(self, client):
        """2 SAR images → 400 INVALID_MODALITY_COMBINATION."""
        payload = {
            "query": "Analyze",
            "images": [
                {"id": "img1", "modality": "sar", "url_or_base64": _TINY_PNG_BASE64},
                {"id": "img2", "modality": "sar", "url_or_base64": _TINY_PNG_BASE64},
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 400
        self._assert_error_shape(response.json(), "INVALID_MODALITY_COMBINATION")

    @pytest.mark.asyncio
    async def test_invalid_base64(self, client):
        """Invalid base64 → 400 UNSUPPORTED_FORMAT."""
        payload = {
            "query": "Test",
            "images": [
                {"id": "img1", "modality": "optical", "url_or_base64": "not-valid-base64!!!"},
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 400
        self._assert_error_shape(response.json(), "UNSUPPORTED_FORMAT")

    @pytest.mark.asyncio
    async def test_empty_query(self, client):
        """Empty query string → 422 (Pydantic validation)."""
        payload = {
            "query": "",
            "images": [
                {"id": "img1", "modality": "optical", "url_or_base64": _TINY_PNG_BASE64},
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        assert response.status_code == 422


# -------------------------------------------------------------------------
# Response shape validation
# -------------------------------------------------------------------------
class TestResponseShape:
    """Validate that all response fields match API_CONTRACT.md exactly."""

    @pytest.mark.asyncio
    async def test_all_response_fields_present(self, client):
        """Ensure every field from the contract is present in the response."""
        payload = {
            "query": "How many buildings?",
            "images": [
                {"id": "img1", "modality": "optical", "url_or_base64": _TINY_PNG_BASE64},
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        data = response.json()

        # Top-level fields
        required_top = {"answer", "confidence", "task", "visual_evidence", "execution_summary"}
        assert required_top.issubset(data.keys()), f"Missing: {required_top - data.keys()}"

        # Visual evidence fields
        ve_required = {"type", "boxes", "mask_base64", "overlay_base64"}
        assert ve_required.issubset(data["visual_evidence"].keys())

        # Execution summary fields
        es_required = {"selected_task", "tool_used", "parameters", "inputs_validated", "latency_ms"}
        assert es_required.issubset(data["execution_summary"].keys())

    @pytest.mark.asyncio
    async def test_confidence_range(self, client):
        """Confidence must be in [0.0, 1.0] per CONTRACT.md §7."""
        payload = {
            "query": "Analyze",
            "images": [
                {"id": "img1", "modality": "optical", "url_or_base64": _TINY_PNG_BASE64},
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        data = response.json()
        assert 0.0 <= data["confidence"] <= 1.0

    @pytest.mark.asyncio
    async def test_task_is_canonical_enum(self, client):
        """Task must be one of the canonical values from CONTRACT.md §5."""
        valid_tasks = {"vqa", "captioning", "detection", "change_detection", "fusion"}
        payload = {
            "query": "What is here?",
            "images": [
                {"id": "img1", "modality": "optical", "url_or_base64": _TINY_PNG_BASE64},
            ],
        }
        response = await client.post("/api/v1/query", json=payload)
        data = response.json()
        assert data["task"] in valid_tasks
